== TwineMedia API Documentation
TwineMedia v1.4.0
API v1

:doctype: api

[preface]
== API Principles
TwineMedia has a REST API.
It stores no session data, and uses JWT tokens for authentication.

Data is passed via query parameters (for `GET` requests), and form encoded data (for everything else).

=== Tools Used In Examples
All API examples require curl to be installed on your system.
These examples were written against the bash shell, which is native to MacOS and most Linux distributions.
Bash syntax is supported with WSL on Windows, but most syntax is identical or similar to Windows PowerShell.


== API Response Structure
API responses possess the following headers:

.API response headers
[width="100%",options="header"]
|=========================================================================================
| Header                           | Value
| Content-Type                     | `application/json`
| Accept                           | `application/json, application/x-www-form-urlencoded`
| Access-Control-Allow-Credentials | The server's configured frontend host OR the request `Origin` header or `*` if none is specified
| Access-Control-Allow-Headers     | `authorization`
|=========================================================================================

Responses are always in JSON format, and may represent a successful


== Authentication
TODO


:numbered!:

[appendix]
== Example Appendix
One or more optional appendixes go here at section level 1.

=== Appendix Sub-section
Sub-section body.


[bibliography]
== Example Bibliography
The bibliography list is a style of AsciiDoc bulleted list.

[bibliography]
.Books
- [[[taoup]]] Eric Steven Raymond. 'The Art of Unix
Programming'. Addison-Wesley. ISBN 0-13-142901-9.
- [[[walsh-muellner]]] Norman Walsh & Leonard Muellner.
'DocBook - The Definitive Guide'. O'Reilly & Associates. 1999.
ISBN 1-56592-580-7.

[bibliography]
.Articles
- [[[abc2003]]] Gall Anonim. 'An article', Whatever. 2003.


[glossary]
== Example Glossary
Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.

[glossary]
A glossary term::
The corresponding (indented) definition.

A second glossary term::
The corresponding (indented) definition.


[colophon]
== Example Colophon
Text at the end of a book describing facts about its production.


[index]
== Example Index
////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
